### ISSUE TITLE
Array has duplicate keys

### ISSUE THREAD

**Issue by szepeviktor** [brainstormforce/astra#1168]
Mainly class-astra-dynamic-css.php and compatibility/class-astra-amp.php has a lot of duplicate keys which do work in CSS although not in PHP:

```php
<?php

$data = array(
    'display' => 'vendor-prefix',
    'display' => 'other-value',
);

var_dump($data);
```

output:

```
array(1) {
  ["display"]=>
  string(11) "other-value"
}
```

**Comment by szepeviktor** [comment]
+1 there are few "stings" (no "r") in the code: https://github.com/brainstormforce/astra/search?q=sting&unscoped_q=sting

+1 remove_action() needs only 3 parameters in inc/compatibility/woocommerce/class-astra-woocommerce.php:607

discovered by https://packagist.org/packages/szepeviktor/phpstan-wordpress
Please consider using it.

**Comment by szepeviktor** [comment]
@patilvikasj Hello! Are these interesting?

**Comment by szepeviktor** [comment]
@Nikschavan Could you take a look at it?

**Comment by Nikschavan** [comment]
- Dynamic CSS - This is a known issue at the moment, As the vendor prefixes are added to the same array key as the CSS property name is the same. These values get overridden at the time of the Array's definition.

- PHPStan is interesting and I have been meaning to add it to our existing projects for a while now.
[szepeviktor/phpstan-wordpress](https://packagist.org/packages/szepeviktor/phpstan-wordpress)  seems an interesting and simple way to configure it for a WordPress project.
I just tried adding it to the project but unfortunately, there seem [PHP fatal errors](https://packagist.org/packages/szepeviktor/phpstan-wordpress) due to function being registered twice from dependency chain.

**Comment by szepeviktor** [comment]
Try this.

/bootstrap.php

```php
<?php

define('ASTRA_THEME_DIR', __DIR__.'/');
define('ASTRA_THEME_URI', '');

class WooCommerce {}
```

/phpstan.neon

```yaml
includes:
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    #level: max
    level: 0
    paths:
        - %currentWorkingDirectory%/inc/
    autoload_files:
        - %currentWorkingDirectory%/bootstrap.php
        # Procedural code
        - %currentWorkingDirectory%/inc/compatibility/edd/edd-common-functions.php
        - %currentWorkingDirectory%/inc/compatibility/woocommerce/woocommerce-common-functions.php
        - %currentWorkingDirectory%/inc/core/deprecated/deprecated-filters.php
        - %currentWorkingDirectory%/inc/core/deprecated/deprecated-functions.php
        - %currentWorkingDirectory%/inc/core/common-functions.php
        - %currentWorkingDirectory%/inc/core/class-theme-strings.php
        - %currentWorkingDirectory%/inc/core/sidebar-manager.php
        - %currentWorkingDirectory%/inc/core/theme-hooks.php
        - %currentWorkingDirectory%/inc/blog/single-blog.php
        - %currentWorkingDirectory%/inc/blog/blog.php
        - %currentWorkingDirectory%/inc/template-tags.php
        - %currentWorkingDirectory%/inc/template-parts.php
        - %currentWorkingDirectory%/inc/extras.php
        - %currentWorkingDirectory%/inc/widgets.php
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters invoked with [34567] parameters, 2 required\.$#'
        - '#^Function do_action invoked with [3456] parameters, 1-2 required\.$#'
        - '#^Function add_query_arg invoked with [123] parameters?, 0 required\.$#'
        - '#^Function add_theme_support invoked with [2345] parameters, 1 required\.$#'
```
