### ISSUE TITLE
Visual issues with LifterLMS certificates

### ISSUE THREAD

**Issue by thomasplevy** [brainstormforce/astra#1585]
Hello,

Today we've discovered a minor visual issue experienced by users using Astra with LifterLMS when they use certificates with a textured/colored background image.

This image depicts the issue:

![Screenshot_2020-01-24_14-39-59](https://user-images.githubusercontent.com/1290739/73109232-73258f00-3eb7-11ea-8ae6-2c0430c0b094.png)

The issue is the white box within the green and black lines. This box displays as a result of the following css rule: 

```css
.ast-separate-container .ast-article-post, .ast-separate-container .ast-article-single {
    background-color: #fff; /* this line causes the issue depicted above */
    border-bottom: 1px solid #eee;
    margin: 0;
    padding: 5.34em 6.67em;
}
```

Which I believe is generated dynamically based on rules added in the customizer.

A small update to the LifterLMS compatibility CSS file resolves the issue by explicitly declaring the background of this element as transparent.

```css
.llms-certificate-container .ast-article-single.llms_certificate {
    background-color: transparent;
}
```

I'll be sending along a pull request to resolve this issue shortly.
