### ISSUE TITLE
Button styling in editor conflicts with Gutenberg block toolbar styles

### ISSUE THREAD

**Issue by ZebulanStanphill** [brainstormforce/astra#3376]
### Describe the bug:
I should be able to use the Gutenberg block editor and have the block controls look like they're supposed to. But instead, they inherit the content button styling. Here are the conflicting styles in `block-editor-styles.css`:

```css
.edit-post-visual-editor .ast-button,
.edit-post-visual-editor .button,
.edit-post-visual-editor button,
.edit-post-visual-editor input,
.edit-post-visual-editor select,
.edit-post-visual-editor textarea {
  color: #808285;
  font-weight: normal;
  font-size: 100%;
  /* Corrects font size not being inherited in all browsers */
  margin: 0;
  /* Addresses margins set differently in IE6/7, F3/4, S5, Chrome */
  vertical-align: baseline;
  /* Improves appearance and consistency in all browsers */
}
```

It seems like the problem is that the styles are not using `.editor-styles-wrapper` to scope them to the content.

### To reproduce:
1. Create a block in the Gutenberg block editor.
2. Look at the block toolbar.

### Expected behavior:
The block controls should look like this:
![image](https://user-images.githubusercontent.com/19592990/135481330-e00f223e-7c57-4f77-b022-83ac2ee4ee29.png)

### Actual behavior:
The block controls look like this:
![image](https://user-images.githubusercontent.com/19592990/135481498-58fe5b3f-7f9a-4e47-9b4d-fd3ccf81d914.png)

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.8.1

Happens both with and without Gutenberg plugin installed. (Tested with 11.6.0.)

### Astra Theme version:
3.7.3
