### ISSUE TITLE
"Wide" block alignment overflows on thinner desktop widths (922px to about 1200px)

### ISSUE THREAD

**Issue by ZebulanStanphill** [brainstormforce/astra#3405]
### Describe the bug:
I should be able to view a page with "Wide"-aligned Gutenberg blocks and not notice any horizontal overflow when using viewports from 922px to about 1200px wide. However, this is not the case. Because the styles for the "Wide" block alignment use hardcoded `-100px` horizontal margins, they cause the edges of the block to go off-screen at certain thin desktop viewport widths that are too wide for the mobile styles (which disable the "Wide" alignment styling entirely) to kick in.

### To reproduce:
1. Create and view a page with the following content:
```html
<!-- wp:columns {"align":"wide","backgroundColor":"ast-global-color-0"} -->
<div class="wp-block-columns alignwide has-ast-global-color-0-background-color has-background"><!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:paragraph {"textColor":"ast-global-color-5"} -->
<p class="has-ast-global-color-5-color has-text-color">this is a Paragraph inside of a Wide-aligned Group.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:paragraph -->
<p>another paragraph</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```
2. Shrink your viewport width to something thin, but not so thin that the mobile styles kick in. About `930px` should make the issue clearly visible.

### Suggested solution:
Change the horizontal margins for "Wide"-aligned blocks to something like `max(calc(50% - 50vw + 20px), -100px)`; this clamps the negative margins to prevent horizontal overflow. In case you're wondering, the `20px` in the `calc` is the standard horizontal padding used by `.ast-container`. This makes the wide blocks have (almost, see next paragraph) the same spacing on the edges as normal-aligned blocks at the mobile viewports.

I've tested this solution locally and it works great, with the one minor annoyance that the horizontal spacing around the "Wide" blocks appears ever-so-slightly less than what it should be, since `vw` units don't take into account the width of the browser's scrollbar. (Why, CSS, why?) But this is barely noticeable, and if it really bothers you, it is possible to fix by [using JS to calculate the scroll bar width and save it to a CSS custom property](https://stackoverflow.com/a/57748743).

**TL;DR:** Replace
```css
.ast-no-sidebar .entry-content .alignwide {
  margin-left: -100px;
  margin-right: -100px;
  max-width: unset;
  width: unset;
}
```
with
```css
:root {
  /* Using a CSS custom property just makes it easier for people to customize. */
  --alignwide-negative-margin: max(calc(50% - 50vw + 20px), -100px);
}
.ast-no-sidebar .entry-content .alignwide {
  margin-left: var(--alignwide-negative-margin);
  margin-right: var(--alignwide-negative-margin);
  max-width: unset;
  width: unset;
}
```

### Screenshots:
![image](https://user-images.githubusercontent.com/19592990/136128917-31f19f8a-19ee-4d3a-ba21-9d0fbdce363e.png)
![image](https://user-images.githubusercontent.com/19592990/136128949-5db8565b-ebac-4bbb-87ae-76712d7f2f16.png)

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.8.1

### Astra Theme version:
3.7.3
