### ISSUE TITLE
[Bug] Blocks misaligned in editor

### ISSUE THREAD

**Issue by JoeIzzard** [brainstormforce/astra#4064]
### Describe the bug:
Some blocks are much further left than others in the editor, specifically I have found Heading, Code and Lists to have this problem, but there may be many more. It isn't a problem on the front end only in the editor.

### To reproduce:
1. Active Astra
2. Create a Post
3. Add some text
4. Add a heading, list or code block

### Expected behavior:
Everything should be aligned in a similar fashion.

### Screenshots:
<img width="1680" alt="astra_bug" src="https://user-images.githubusercontent.com/3457283/150414033-1c7fde16-6e59-4698-b7fb-7b255a79c9bf.png">

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.8.3

### Astra Theme version:
3.7.6

**Comment by JoeIzzard** [comment]
I have done some digging at it seems to be this bit of CSS that is causing the issue:

```css
.block-editor-block-list__layout.is-root-container > .wp-block:not([data-align=full]):not([data-align=wide]):not([data-align=left]):not([data-align=right]):not(p.wp-block-paragraph):not(.wp-block-cover):not(.wp-block-group):not(.wp-block-columns):not(.wp-block-media-text) {
    max-width: 1256px;
}
```

Which is added dynamically to the Head of the edit page by Astra, in a style block with the ID `astra-block-editor-styles-inline-css`.

Not sure where this comes from though, my searching of the repo isn't returning anything obvious.

I have tried an altered version of the filter from #3749 but didn't have much luck, but may have gotten part of my modification wrong. Specifically I have tried:

```php
apply_filters( 'astra-block-editor-styles-inline-css', $parse_css );
add_filter('astra-block-editor-styles-inline-css', 'astracss_fixer');
function astracss_fixer($parse_css) {
    $bad_css = '.block-editor-block-list__layout.is-root-container > .wp-block:not([data-align=full]):not([data-align=wide]):not([data-align=left]):not([data-align=right]):not(p.wp-block-paragraph):not(.wp-block-cover):not(.wp-block-group):not(.wp-block-columns):not(.wp-block-media-text) {
        max-width: 1256px;
    }';
    $parse_css = str_replace($bad_css, "", $parse_css);
    return $parse_css;
}
```
