### ISSUE TITLE
Query Loop Block Padding broken in Post Layout

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4963]
Hi,
this bug has already been reported in the privat astra bug tracker for paid users. Ticket ID: 287384

Workaround:
```css
.wp-block-query > ul.wp-block-post-template.is-flex-container.is-flex-container>li {    
    padding: 0px;
}
.wp-block-query > ul.wp-block-post-template.is-layout-flow.is-flex-container {
    margin: 0px;
}
```

The issue is basically that a query loop block inside a boxed layout will look like this:
![grafik](https://user-images.githubusercontent.com/6888294/214616516-bfba301b-5402-4fd8-8216-0cb81ef1e427.png)

The issue happens on WP 6.1.1 and Astra 4.0.2. As I said, more details in the private ticket where nobody is looking at, sadly. I hope I have more luck here.
