### ISSUE TITLE
Related Posts Section has unwanted padding

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4964]
### Describe the bug:
Checkout this related posts section:
![grafik](https://user-images.githubusercontent.com/6888294/214617589-c452edf3-ca68-49d7-8b08-63f0cf38f5dc.png)

### To reproduce:
I found out that the related post issue only appears, because I have set
the customizer Setting Blog->Single Post->Design->Post Spacing->Inside
to 5EM. But this padding is also applied to the related post box, which
should not happen, or maybe they should get their own setting for
spacing. I have attached a screenshot for that.

Workaround:
```css
/*astra bug related posts padding*/
.ast-separate-container.ast-single-post .ast-single-related-posts-container .ast-related-posts-wrapper .ast-article-single {
	padding: 0;
}
```

### Expected behavior:
There should be no padding for the related posts that is affected by the post setting. Either remove it or make it configurable.

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.1.1

### Astra Theme version:
4.0.2
